version: "3.9"

services:
  database:
    image: postgres
    container_name: database_delivery
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
